api_platform:
    title: "API plateforme - auteur: adil lemraoui"
    description: 'API web services pour des blogs'
    show_webby: false
    version: 0.0.1
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    #Format
    formats:
        jsonld:  ['application/ld+json']
        jsonhal: ['application/hal+json']
        xml:     ['application/xml', 'text/xml']
        json:    ['application/json']
        yaml:    ['application/x-yaml']  
        csv:     ['text/csv']
        html:    ['text/html']
